#!/bin/bash
set -e

echo "=========================================="
echo "Create Bootable ZuluSCSI Disk"
echo "=========================================="
echo ""

# Config
OUTPUT_DIR="$HOME/Desktop/ZuluSCSI-BOOT"
DISK_SIZE=239  # MB (EmaxForge standard)
SCSI_ID=1      # EMAX II boots from SCSI ID 1
BANK_DIR="$HOME/clawd/Emax Drive"

# Clean old output
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

echo "[1/5] Creating HD10.hda (239 MB with OS)..."
cd ~/clawd/EmaxForge

# Use CLI tool to create boot disk
./.build/EmaxForge.app/Contents/MacOS/EmaxForge create \
  --name HD10 \
  --size $DISK_SIZE \
  --os rev2.14 \
  --output "$OUTPUT_DIR/HD10.hda"

if [ ! -f "$OUTPUT_DIR/HD10.hda" ]; then
    echo "❌ Failed to create disk image!"
    exit 1
fi

echo "✅ HD10.hda created ($(du -h "$OUTPUT_DIR/HD10.hda" | cut -f1))"
echo ""

echo "[2/5] Finding sample banks..."
# Find some banks from Peter's collection
BANKS=($(find "$BANK_DIR" -name "*.EB2" -type f | head -10))

if [ ${#BANKS[@]} -eq 0 ]; then
    echo "⚠️  No banks found in $BANK_DIR"
    echo "   Creating disk with OS only (you can add banks later)"
else
    echo "Found ${#BANKS[@]} banks to import:"
    for bank in "${BANKS[@]}"; do
        basename "$bank"
    done
    echo ""
    
    echo "[3/5] Importing banks to HD10.hda..."
    echo "⚠️  NOTE: Bank import requires write support (coming in Phase 2)"
    echo "   For now, disk contains OS + INIT BANK only"
    echo "   You can add banks manually in EmaxForge or EmaxForge"
fi
echo ""

echo "[4/5] Creating zuluscsi.ini..."
cat > "$OUTPUT_DIR/zuluscsi.ini" << 'EOF'
# ZuluSCSI Config for EMAX II Boot Disk
# Generated by EmaxForge

[SCSI1]
Type = Fixed
SectorSize = 512
# HD10.hda - Boot disk with OS
EOF

echo "✅ zuluscsi.ini created"
echo ""

echo "[5/5] Creating README..."
cat > "$OUTPUT_DIR/README.txt" << 'EOF'
ZuluSCSI Boot Disk for EMAX II
===============================

Files:
------
HD10.hda        - Boot disk (239 MB) with EMAX II OS v2.14
zuluscsi.ini    - SCSI configuration (ID 1)
README.txt      - This file

Installation:
-------------
1. Format SD card as FAT32
2. Copy ALL files to SD card root
3. Insert SD into ZuluSCSI Pico
4. Connect to EMAX II SCSI port
5. Power on EMAX II

What's Inside:
--------------
- EMAX II Operating System v2.14
- INIT BANK (required for boot)
- ~88 free bank slots

SCSI Configuration:
-------------------
SCSI ID: 1 (EMAX II boots from ID 1, NOT 0!)
Boot disk: HD10.hda
Data disks: Create HD20.hda, HD30.hda for more storage

Adding Banks:
-------------
Option A: Use EmaxForge (Mac)
  - Open HD10.hda in EmaxForge
  - Drag .EB2 files to disk
  - Save (Phase 2 feature - coming soon!)

Option B: Use EmaxForge (Windows via Wine/Whisky)
  - Open HD10.hda in EmaxForge
  - Import banks via Bank menu
  - Save disk

Option C: Create new banks on EMAX II
  - Boot EMAX II
  - Record/edit samples
  - Save to HD10

Troubleshooting:
----------------
EMAX II won't boot?
  → Check SCSI ID (must be 1)
  → Check cable connections
  → Try power cycle
  → Verify SD card is FAT32
  → Check ZuluSCSI LED (should blink on access)

No sound?
  → Select a bank (not just OS)
  → Check audio outputs
  → Try playing a note

Need help?
  → EmaxForge GitHub: https://github.com/username/emaxforge
  → ZuluSCSI Docs: https://zuluscsi.com

Created by EmaxForge - EMAX II Disk Manager for macOS
EOF

echo "✅ README.txt created"
echo ""

echo "=========================================="
echo "✅ ZuluSCSI Boot Disk Complete!"
echo "=========================================="
echo ""
echo "Output directory:"
echo "  $OUTPUT_DIR"
echo ""
echo "Files created:"
ls -lh "$OUTPUT_DIR"
echo ""
echo "📦 Total size: $(du -sh "$OUTPUT_DIR" | cut -f1)"
echo ""
echo "Next steps:"
echo "  1. Format SD card as FAT32"
echo "  2. Copy all files from $OUTPUT_DIR to SD"
echo "  3. Insert SD into ZuluSCSI Pico"
echo "  4. Boot EMAX II! 🚀"
echo ""
echo "⚠️  IMPORTANT:"
echo "   - EMAX II boots from SCSI ID 1 (HD10.hda)"
echo "   - Disk contains OS + INIT BANK"
echo "   - Add your own banks via EmaxForge or EmaxForge"
echo ""
